### ISSUE TITLE
Detailed Contest Report

### ISSUE THREAD

**Issue by bwornom7** [bwornom7/open-contest#11]
Add a button to the leaderboard screen labeled "Detailed Report". When clicked, this should display a report like this:

[Sample report](https://protect.bju.edu/wiki/download/attachments/1737261/MU2018Standings.pdf?version=1&modificationDate=1519675981000)

**Comment by cshean** [comment]
Has bugs, needs fixing for integration

**Comment by cshean** [comment]
Not completely done but finished as I can get it in the time I have
